# Generated by Django 4.2.7 on 2024-02-19 19:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('short_content', models.CharField(max_length=127, verbose_name='Short Content')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('icon', models.CharField(choices=[('1', 'TEST'), ('2', 'TEST'), ('3', 'TEST'), ('4', 'TEST'), ('5', 'TEST'), ('6', 'TEST'), ('7', 'TEST')], max_length=150, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
